import { type ClassValue, clsx } from "clsx";
import { twMerge } from "tailwind-merge";

export function cn(...inputs: ClassValue[]) {
  return twMerge(clsx(inputs));
}

export function generateRandomId() {
  // Length of the id should be 10
  return Math.random().toString(36).substr(2, 10);
}

// [
//   {
//     checked: true,
//     description: "",
//     disabled: false,
//     label: "Full Name",
//     name: "name_5168914938",
//     placeholder: "MS Dhoni",
//     required: true,
//     rowIndex: 0,
//     type: "",
//     value: "",
//     variant: "Input",
//   },
//   {
//     checked: true,
//     description: "enter image url",
//     disabled: false,
//     label: "Profile Picure",
//     name: "name_6197189997",
//     placeholder: "https://...",
//     required: false,
//     rowIndex: 0,
//     type: "text",
//     value: "",
//     variant: "Input",
//   },
//   {
//     checked: true,
//     description: "your preferred fiels",
//     disabled: false,
//     label: "Category",
//     name: "name_4027962805",
//     placeholder: "select ",
//     required: true,
//     rowIndex: 0,
//     type: "",
//     value: "",
//     variant: "Multi Select",
//   },
//   {
//     checked: true,
//     description: "all Languages You are fluent in",
//     disabled: false,
//     label: "Languages",
//     name: "name_4763535406",
//     placeholder: "Placeholder",
//     required: true,
//     rowIndex: 0,
//     type: "",
//     value: "",
//     variant: "Multi Select",
//   },
//   {
//     checked: true,
//     description: "",
//     disabled: false,
//     label: "Email",
//     name: "name_8886735196",
//     placeholder: "xyz@gm.com",
//     required: true,
//     rowIndex: 0,
//     type: "email",
//     value: "",
//     variant: "Input",
//   },
//   {
//     checked: true,
//     description: "",
//     disabled: false,
//     label: "Education",
//     name: "name_5350628047",
//     placeholder: "",
//     required: true,
//     rowIndex: 0,
//     type: "",
//     value: "",
//     variant: "Input",
//   },
//   {
//     checked: true,
//     description: "This is your public display name.",
//     disabled: false,
//     label: "Experience",
//     name: "name_1085724306",
//     placeholder: "2+ years",
//     required: true,
//     rowIndex: 0,
//     type: "",
//     value: "",
//     variant: "Input",
//   },
//   {
//     checked: true,
//     description: "write a bio",
//     disabled: false,
//     label: "About yourself",
//     name: "name_0859382355",
//     placeholder: "I am ...",
//     required: true,
//     rowIndex: 0,
//     type: "",
//     value: "",
//     variant: "Textarea",
//   },
//   {
//     checked: true,
//     description: "Enter your phone number.",
//     disabled: false,
//     label: "Phone number",
//     name: "name_0436784088",
//     placeholder: "Placeholder",
//     required: true,
//     rowIndex: 0,
//     type: "",
//     value: "",
//     variant: "Phone",
//   },
//   {
//     checked: true,
//     description: "",
//     disabled: false,
//     label: "Office address",
//     name: "name_2828577374",
//     placeholder: "",
//     required: true,
//     rowIndex: 0,
//     type: "",
//     value: "",
//     variant: "Input",
//   },
// ];
